# -------------------- Easy reload --------------------
unbind r
bind r source-file ~/.tmux.conf

# -------------------- Utility --------------------
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"
set -sa terminal-overrides ",xterm*:Tc"
set -sg escape-time 10
set -g mouse on

# -------------------- Rebind Leader --------------------
unbind C-b
set -g prefix C-a

# -------------------- Copy / Scroll --------------------
set-window-option -g mode-keys vi

# -------------------- Pane Bindings --------------------
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind '"' split-window -v -c "#{pane_current_path}"
bind '%' split-window -h -c '#{pane_current_path}'

# -------------------- Pane Indexing --------------------
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# -------------------- Status Bar --------------------
set-option -g status-position top
set -g status-interval 5
set -g status-style "bg=default,fg=default"
set -g status-left ""
set -g status-right ""
set -g window-status-format " #I:#{=12:pane_current_command} "
set -g window-status-current-format " #I:#{=12:pane_current_command}* "
set -g window-status-style "fg=colour8,bg=default"
set -g window-status-current-style "fg=white,bg=default"
set -g window-status-separator ""

# -------------------- Plugins --------------------
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
